FROM alpine:3.6
MAINTAINER Gregoire Lejeune <gregoire.lejeune@free.fr>

# Install Essential packages for Erlang and Elixir
RUN apk --update add zlib ncurses openssl unixodbc && rm -rf /var/cache/apk/*

